name: Build Extension

on:
  push:
    tags:
      - '*'

jobs:

  build:
  
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: VirtualDesktopTimecodeServer.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Get Application Version
      id: get_version
      uses: battila7/get-version-action@v2
        
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Create the app package
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}
    
    - name: Upload Artifact 1
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin\Release\net471\VirtualDesktopTimecodeServer.dll
        asset_name: VirtualDesktopTimecodeServer_${{ steps.get_version.outputs.version }}.dll
        tag: ${{ github.ref }}
        overwrite: true
        
    - name: Upload Artifact 2
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: inject.bat
        asset_name: inject_${{ steps.get_version.outputs.version }}.bat
        tag: ${{ github.ref }}
        overwrite: true
